# Generated by Django 3.2.5 on 2021-08-30 09:14

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('text_id', models.CharField(help_text='на англ, без пробелов, с нижним подчеркиванием', max_length=255, verbose_name='Название- идентификатор')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Сообщение бота',
                'verbose_name_plural': 'Сообщения бота',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Тип компании',
                'verbose_name_plural': 'Типы компаний',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, null=True, verbose_name='Заголовок')),
                ('custom_company_type', models.CharField(blank=True, max_length=140, null=True, verbose_name='Кастомный тип компании')),
                ('company_name', models.CharField(max_length=140, null=True, verbose_name='Компания')),
                ('bot_name', models.CharField(max_length=140, null=True, verbose_name='Имя бота')),
                ('color', models.JSONField(blank=True, null=True, verbose_name='Цвет')),
                ('construct', models.JSONField(blank=True, null=True)),
                ('dialog_config', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('company_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.companytype', verbose_name='Вид деятельности')),
            ],
            options={
                'verbose_name': 'Конструктор',
                'verbose_name_plural': 'Конструкторы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='images/', verbose_name='Image')),
                ('image_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('color', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True, verbose_name='Имя')),
                ('const', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='constructor.constructor', verbose_name='Конструктор')),
            ],
            options={
                'verbose_name': 'Сотрудника',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('duration', models.TimeField(blank=True, null=True)),
                ('const', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.constructor', verbose_name='Конструктор')),
                ('staff', models.ManyToManyField(blank=True, to='constructor.Staff', verbose_name='Сотрудники')),
            ],
            options={
                'verbose_name': 'Услугу',
                'verbose_name_plural': 'Услуги',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('details', models.TextField(max_length=300, null=True, verbose_name='Описание')),
                ('color', models.CharField(default='#000', max_length=300, verbose_name='Цвет')),
                ('status', models.CharField(choices=[('FR', 'Free'), ('BS', 'Busy')], default='FR', max_length=300, verbose_name='Статус')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('phone', models.CharField(max_length=300, null=True, verbose_name='Номер телефона')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Начало приема')),
                ('end', models.DateTimeField(verbose_name='Окончание приема')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='constructor.staff', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DefaultStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True, verbose_name='Имя')),
                ('company_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.companytype', verbose_name='Тип компании')),
            ],
            options={
                'verbose_name': 'Стандарного Сотрудника',
                'verbose_name_plural': 'Стандартные Сотрудники',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DefaultService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('duration', models.TimeField(blank=True, null=True)),
                ('company_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.companytype', verbose_name='Тип компании')),
                ('staff', models.ManyToManyField(blank=True, to='constructor.DefaultStaff', verbose_name='Сотрудники')),
            ],
            options={
                'verbose_name': 'Стандартную Услугу',
                'verbose_name_plural': 'Стандартные Услуги',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DefaultCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('company_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.companytype', verbose_name='Тип компании')),
                ('service', models.ManyToManyField(blank=True, to='constructor.DefaultService', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Стандартную Категорию',
                'verbose_name_plural': 'Стандартные Категории',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='constructor',
            name='logo',
            field=models.ManyToManyField(blank=True, related_name='constructors', to='constructor.Image'),
        ),
    ]
