# Generated by Django 3.2.5 on 2021-08-30 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constructor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='category',
            name='const',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='constructor.constructor', verbose_name='Конструктор'),
        ),
        migrations.AddField(
            model_name='category',
            name='service',
            field=models.ManyToManyField(blank=True, to='constructor.Service', verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='bottext',
            name='const',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.constructor', verbose_name='Конструктор'),
        ),
    ]
