# Generated by Django 3.2.5 on 2021-08-30 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructor',
            name='bot_name',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Имя бота'),
        ),
        migrations.AlterField(
            model_name='constructor',
            name='company_name',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Компания'),
        ),
        migrations.RemoveField(
            model_name='constructor',
            name='logo',
        ),
        migrations.AddField(
            model_name='constructor',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constructors', to='constructor.image'),
        ),
        migrations.AlterField(
            model_name='constructor',
            name='name',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Заголовок'),
        ),
    ]
