# Generated by Django 3.2.5 on 2021-08-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_auto_20210830_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructor',
            name='logo',
        ),
        migrations.AddField(
            model_name='constructor',
            name='logo',
            field=models.ManyToManyField(blank=True, related_name='constructors', to='constructor.Image'),
        ),
    ]
