version: '3.7'

services:
  backend:
    build:
      context: ./backend
    command: /start_prod.sh
    networks:
      - django-nginx
    volumes:
      - .:/code
      - static_volume:/backend/staticfiles
      - media_volume:/backend/mediafiles

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
    networks:
      - django-nginx
    volumes:
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/backend/staticfiles
      - media_volume:/backend/mediafiles
    depends_on:
      - backend

volumes:
  static_volume:
  media_volume:

networks:
  django-nginx:
    driver: bridge
